spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pythagore
    username: admin
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: true
  jpa.properties:
    hibernate:
      jdbc:
        time_zone: UTC
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000