server:
  port: ${SERVER_PORT}
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: ${SPRING_JPA_DATABASE_PLATFORM}
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: create-drop
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_ADRESS}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
aws:
  s3Url: ${S3_URL}
  elasticUrl: ${ELASTIC_URL}