spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pythagore
    username: admin
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: true
  jpa.properties:
    hibernate:
      jdbc:
        time_zone: UTC
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_ADRESS}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true