version: '3'
services:
  postgres:
    image: postgres:16
    container_name: pythagore_db
    env_file:
      - ../env/db-env.env
    ports:
      - "5432:5432"
    volumes:
      - /Users/admin/Desktop/DB:/var/lib/postgresql/data
